### ISSUE TITLE
Problem z "cabal haddock"

### ISSUE THREAD

**Issue by Elrohil44** [maxiwoj/HaskellProject#10]
Po wykonaniu czynności wymienionych w pliku README, nie udało się wywołać "cabal haddock".
Zgodnie z zaleceniami narzędzia, użyliśmy "cabal configure", a następnie spróbowaliśmy ponownie, ale mimo wszystko otrzymaliśmy poniższy błąd:
![obraz](https://cloud.githubusercontent.com/assets/19774870/22291429/ad111456-e306-11e6-90ba-e83b31172528.png)

**Comment by Chimstaz** [comment]
Zmieniłem nazwę pliku z 'src/quicksort.hs' na 'src/Quicksort.hs'. Być może na linuxie cabal rozróżnia wielkość liter w nazwach plików.
